In [1]:
#一维
import numpy as np 
data1=[1,2,3,4,5]
array1=np.array(data1)
print(array1)

[1 2 3 4 5]


In [2]:
#二维
data2=[[1,2,3],[4,5,6]]
array2=np.array(data2)
print(array2)

[[1 2 3]
 [4 5 6]]


In [3]:
#三维
data2=[[[1,2,3],[4,5,6]]]
array2=np.array(data2)
print(array2)

[[[1 2 3]
  [4 5 6]]]


# series

## 基础

Series：一维数组，与Numpy中的一维array类似。二者与Python基本的数据结构List也很相近。Series如今能保存不同种数据类型，字符串、boolean值、数字等都能保存在Series中。 Series用于存储一行或一列数据，以及与之相关的索引集合。 使用方法： Series([数据1，数据2，……],index=[索引1，索引2，……])

In [4]:
from pandas import Series
s = Series([1,4,'ww','tt'])  #s是一个对象，一维数组

In [5]:
s

0     1
1     4
2    ww
3    tt
dtype: object

In [7]:
s[2] #不需要说明位置

'ww'

In [8]:
s[1:]

1     4
2    ww
3    tt
dtype: object

## s对象方法

In [9]:
s.index

RangeIndex(start=0, stop=4, step=1)

In [10]:
s.values

array([1, 4, 'ww', 'tt'], dtype=object)

## 赋值

In [11]:
s2 = Series(['wangxing','man',24],index=['name','sex','age'])

## 读取值

In [14]:
s2['name']
s2[0]

'wangxing'

## 更改值

In [15]:
s2['name'] = '李玲鞠'
print(s2)

name    李玲鞠
sex     man
age      24
dtype: object


## 像字典

In [16]:
sd = {'python':9000,'c++':9001,'c#':9000}
s3=Series(sd)
s3

python    9000
c++       9001
c#        9000
dtype: int64

# DataFrame

## 基础

DataFrame：二维的表格型数据结构,用于存储多行和多列的数据集合。可以将DataFrame理解为Series的容器，类似于Excel的二维表格。它的竖行称之为 columns，横行跟前面的 Series 一样，称之为 index，也就是说可以通过 columns 和 index 来确定一个主句的位置。（series容器）

In [17]:
from pandas import DataFrame
data = {"name":['google','baidu','alibaba'],"marks":[100,200,300],"price":[1,2,3]}
f1 = DataFrame(data) 
print(f1) 

      name  marks  price
0   google    100      1
1    baidu    200      2
2  alibaba    300      3


## 访问！ iloc\loc

In [22]:
f1.at[1,'name']

'baidu'

先行后列用at，先列后行不用at

In [50]:
print(f1.at[1,'name'])
print(f1['name'][1])

baidu
baidu


In [49]:
print(f4['name'][0]) #访问（列名、行名）位置的数据
print('------1------')
print(f4['name'])  #访问列
print('------2------')
print(f4[1:])      #访问行（左闭右开区间）
print('------3------')
print(f4.iloc[1:,:2]) #访问块（第一个是行范围，第二个是列范围，都是左闭右开区
print('------4------')
print(f4.loc['b':,:'marks']) #访问块（第一个是行范围，第二个是列范围，都是标签名）

google
------1------
a     google
b      baidu
c    alibaba
Name: name, dtype: object
------2------
      name  marks  price
b    baidu    200      2
c  alibaba    300      3
------3------
      name  marks
b    baidu    200
c  alibaba    300
------4------
      name  marks
b    baidu    200
c  alibaba    300


### iloc\loc 高级用法

In [1]:
from pandas import DataFrame
data = {"name":['google','baidu','alibaba'],"marks":[100,200,300],"price":[1,2,3]}
f1 = DataFrame(data) 
print(f1) 

      name  marks  price
0   google    100      1
1    baidu    200      2
2  alibaba    300      3


利用arry数组True、False取值

In [2]:
a=([True,False,False])
f1.iloc[:,a]

name
0   google
1    baidu
2  alibaba

利用loc增加行列

iloc是取下标，不能超出数据，但loc是取标签，可以增加

In [4]:
f1.loc[3,:]=None
f1

name  marks  price
0   google  100.0    1.0
1    baidu  200.0    2.0
2  alibaba  300.0    3.0
3     None    NaN    NaN

## 更改列顺序

In [23]:
f3=DataFrame(data,columns=['name','price','marks'])
f3

name  price  marks
0   google      1    100
1    baidu      2    200
2  alibaba      3    300

## 更改索引

In [24]:
f4 = DataFrame(data,columns=['name','marks','price'], index=['a','b','c'])
f4

name  marks  price
a   google    100      1
b    baidu    200      2
c  alibaba    300      3

## 修改数据

In [51]:
f4.loc['a','name']='youtube' #修改数据
f4

name  marks  price
a  youtube    100      1
b    baidu    200      2
c  alibaba    300      3

# 作业

## 存取CSV

In [52]:
f4.to_csv('E:\作业\Python商业数据分析\c2-1.csv')

In [58]:
import pandas as pd
pd.read_csv('E:\作业\Python商业数据分析\c2-1.csv')

Unnamed: 0     name  marks  price
0          a  youtube    100      1
1          b    baidu    200      2
2          c  alibaba    300      3

## 存取Excel

In [59]:
f4.to_excel('E:\作业\Python商业数据分析\c2-1.xlsx')

In [63]:
pd.read_excel('E:\作业\Python商业数据分析\c2-1.xlsx')

Unnamed: 0     name  marks  price
0          a  youtube    100      1
1          b    baidu    200      2
2          c  alibaba    300      3

读取并创建数据表（dateframe）

In [66]:
df=pd.DataFrame(pd.read_excel('E:\作业\Python商业数据分析\c2-1.xlsx'))
df

Unnamed: 0     name  marks  price
0          a  youtube    100      1
1          b    baidu    200      2
2          c  alibaba    300      3

## 挖地兔tushare数据存取

### 导入tushare包并获取数据

In [1]:
import tushare as ts
df = ts.get_hist_data('000875')
df.head()

本接口即将停止更新，请尽快使用Pro版接口：https://tushare.pro/document/2


open  high  close   low      volume  price_change  p_change  \
date                                                                      
2022-03-03  8.85  8.90   8.66  8.58   680082.56         -0.07     -0.80   
2022-03-02  8.87  8.93   8.73  8.58   954737.75         -0.17     -1.91   
2022-03-01  8.87  9.05   8.90  8.80  1007274.25          0.04      0.45   
2022-02-28  8.60  9.00   8.86  8.53  1682938.75          0.16      1.84   
2022-02-25  8.30  8.85   8.70  8.09  2060748.75          0.63      7.81   

              ma5   ma10   ma20       v_ma5      v_ma10     v_ma20  turnover  
date                                                                          
2022-03-03  8.770  8.312  8.192  1277156.41  1019255.21  815503.91      2.78  
2022-03-02  8.652  8.230  8.137  1459118.88  1001451.40  836756.81      3.90  
2022-03-01  8.468  8.141  8.106  1360077.76   949909.28  826215.50      4.12  
2022-02-28  8.218  8.045  8.066  1275711.31   889782.17  829984.85      6.88  
2022-02-25  8.026  7.950  8.053  1073985.56   792812.97  800136.09      8.43

### 保存数据

保存为CSV

In [3]:
df.to_csv('E:\作业\Python商业数据分析\\000875_1.csv') #直接保存,不转译加r''
# df.to_csv(r'E:\作业\Python商业数据分析\000875_2.csv',columns=['open','high','close','low']) #选择数据保存

保存为excel

In [4]:
df.to_excel('E:\作业\Python商业数据分析\\000875_1.xlsx') #直接保存,不转译加r''
# df.to_excel(r'E:\作业\Python商业数据分析\000875_2.xlsx',columns=['open','high','close','low']) #选择数据保存
# df.to_excel(r'E:\作业\Python商业数据分析\000875_3.xlsx',startrow=2,startcol=5) #从第三行第六列开始存

### 读取数据

读取csv

In [9]:
import pandas as pd
import numpy as np
df = pd.read_csv('E:\作业\Python商业数据分析\\000875_1.csv')
df.head(n=2)

date  open  high  close   low     volume  price_change  p_change    ma5   ma10   ma20       v_ma5      v_ma10     v_ma20  turnover
0  2022-03-03  8.85  8.90   8.66  8.58  680082.56         -0.07     -0.80  8.770  8.312  8.192  1277156.41  1019255.21  815503.91      2.78
1  2022-03-02  8.87  8.93   8.73  8.58  954737.75         -0.17     -1.91  8.652  8.230  8.137  1459118.88  1001451.40  836756.81      3.90

读取excel

In [8]:
import pandas as pd
import numpy as np
df = pd.read_excel('E:\作业\Python商业数据分析\\000875_1.xlsx')
df.head(n=2)

date  open  high  close   low     volume  price_change  p_change    ma5   ma10   ma20       v_ma5      v_ma10     v_ma20  turnover
0  2022-03-03  8.85  8.90   8.66  8.58  680082.56         -0.07     -0.80  8.770  8.312  8.192  1277156.41  1019255.21  815503.91      2.78
1  2022-03-02  8.87  8.93   8.73  8.58  954737.75         -0.17     -1.91  8.652  8.230  8.137  1459118.88  1001451.40  836756.81      3.90

### 读取数据到内存

#### 读取挖地兔数据

In [3]:
import tushare as ts
import pandas as pd
import numpy as np
data = pd.DataFrame()
data1 = ts.get_hist_data('600000')
data1 = data1['close']
data1 = data1[::-1]       #日期从远到进结束
data['600000']= data1
data2 = ts.get_hist_data('000980')
data2 = data2['close']
data2 = data2[::-1]
data['000980']= data2
data3 = ts.get_hist_data('000981')
data3 = data3['close']
data3 = data3[::-1]
data['000981']= data3
data.info()               #查看数据信息

本接口即将停止更新，请尽快使用Pro版接口：https://tushare.pro/document/2
本接口即将停止更新，请尽快使用Pro版接口：https://tushare.pro/document/2
本接口即将停止更新，请尽快使用Pro版接口：https://tushare.pro/document/2
<class 'pandas.core.frame.DataFrame'>
Index: 602 entries, 2019-09-09 to 2022-03-07
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   600000  602 non-null    float64
 1   000980  586 non-null    float64
 2   000981  592 non-null    float64
dtypes: float64(3)
memory usage: 18.8+ KB


#### 清除数据空值

In [4]:
data = data.dropna()
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 576 entries, 2019-09-09 to 2022-03-07
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   600000  576 non-null    float64
 1   000980  576 non-null    float64
 2   000981  576 non-null    float64
dtypes: float64(3)
memory usage: 18.0+ KB


#### 显示前后五条

In [5]:
data.head()

600000  000980  000981
date                              
2019-09-09   11.75    3.81    1.54
2019-09-10   11.85    3.86    1.54
2019-09-11   11.95    3.87    1.54
2019-09-12   12.00    3.90    1.54
2019-09-16   11.93    3.87    1.49

In [6]:
data.tail()

600000  000980  000981
date                              
2022-03-01    8.44    4.32    1.81
2022-03-02    8.42    4.37    1.72
2022-03-03    8.46    4.18    1.63
2022-03-04    8.40    4.02    1.57
2022-03-07    8.29    3.82    1.65

#### 取列数据

In [10]:
data=data[['600000','000980']]
print(data)

            600000  000980
date                      
2019-09-09   11.75    3.81
2019-09-10   11.85    3.86
2019-09-11   11.95    3.87
2019-09-12   12.00    3.90
2019-09-16   11.93    3.87
...            ...     ...
2022-03-01    8.44    4.32
2022-03-02    8.42    4.37
2022-03-03    8.46    4.18
2022-03-04    8.40    4.02
2022-03-07    8.29    3.82

[576 rows x 2 columns]


#### iloc和loc读取数据

In [16]:
print(data.iloc[:6,:])
print('---------------------------')
print(data.loc[:'2019-09-17',:])

            600000  000980
date                      
2019-09-09   11.75    3.81
2019-09-10   11.85    3.86
2019-09-11   11.95    3.87
2019-09-12   12.00    3.90
2019-09-16   11.93    3.87
2019-09-17   11.81    3.73
---------------------------
            600000  000980
date                      
2019-09-09   11.75    3.81
2019-09-10   11.85    3.86
2019-09-11   11.95    3.87
2019-09-12   12.00    3.90
2019-09-16   11.93    3.87
2019-09-17   11.81    3.73


### tushare pro

In [6]:
import tushare as ts
import pandas as pd
pd.set_option('expand_frame_repr',False) #显示所有列
ts.set_token('3beebb3ed233f16bad857c626a68e66348a2eacc07ba53b672d51480') #token号
pro = ts.pro_api() #使用pro接口
stock_data = pro.daily(ts_code='000001.sz',start_date='20220220',end_date='20220303') #获取数据
print(stock_data.head())
print('---------------------------------------------------------------------------------------------------')
print(stock_data.tail())

     ts_code trade_date   open   high    low  close  pre_close  change  pct_chg        vol       amount
0  000001.SZ   20220303  15.73  15.81  15.63  15.71      15.68    0.03   0.1913  578285.05   908171.588
1  000001.SZ   20220302  15.79  15.87  15.66  15.68      15.92   -0.24  -1.5075  760760.86  1196321.948
2  000001.SZ   20220301  15.79  15.95  15.62  15.92      15.75    0.17   1.0794  935040.34  1474693.965
3  000001.SZ   20220228  15.90  15.92  15.62  15.75      15.90   -0.15  -0.9434  723990.45  1137154.094
4  000001.SZ   20220225  15.99  16.08  15.87  15.90      15.91   -0.01  -0.0629  726397.07  1157890.268
---------------------------------------------------------------------------------------------------
     ts_code trade_date   open   high    low  close  pre_close  change  pct_chg         vol       amount
4  000001.SZ   20220225  15.99  16.08  15.87  15.90      15.91   -0.01  -0.0629   726397.07  1157890.268
5  000001.SZ   20220224  16.13  16.15  15.80  15.91      16.19   -